AddModRPCHandler("DSTAchievement", "potion", function(player)
	player.components.allachivcoin:potioncoin(player)
end)

--特殊
AddModRPCHandler("DSTAchievement", "level120", function(player)
	player.components.allachivcoin:level120coin(player)
end)
AddModRPCHandler("DSTAchievement", "abigaillevelup", function(player)
	player.components.allachivcoin:abigaillevelupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "abigailclone", function(player)
	player.components.allachivcoin:abigailclonecoin(player)
end)
AddModRPCHandler("DSTAchievement", "bloodangry", function(player)
	player.components.allachivcoin:bloodangrycoin(player)
end)
AddModRPCHandler("DSTAchievement", "balloonlevelup", function(player)
	player.components.allachivcoin:balloonlevelupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "ballooninspire", function(player)
	player.components.allachivcoin:ballooninspirecoin(player)
end)
AddModRPCHandler("DSTAchievement", "wescheat", function(player)
	player.components.allachivcoin:wescheatcoin(player)
end)
AddModRPCHandler("DSTAchievement", "callspider", function(player)
	player.components.allachivcoin:callspidercoin(player)
end)
AddModRPCHandler("DSTAchievement", "spiderstronger", function(player)
	player.components.allachivcoin:spiderstrongercoin(player)
end)
AddModRPCHandler("DSTAchievement", "bernielevelup", function(player)
	player.components.allachivcoin:bernielevelupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "linghtermore", function(player)
	player.components.allachivcoin:linghtermorecoin(player)
end)
AddModRPCHandler("DSTAchievement", "gearuse", function(player)
	player.components.allachivcoin:gearusecoin(player)
end)
AddModRPCHandler("DSTAchievement", "callmerm", function(player)
	player.components.allachivcoin:callmermcoin(player)
end)
AddModRPCHandler("DSTAchievement", "mermstronger", function(player)
	player.components.allachivcoin:mermstrongercoin(player)
end)
AddModRPCHandler("DSTAchievement", "soulmore", function(player)
	player.components.allachivcoin:soulmorecoin(player)
end)
AddModRPCHandler("DSTAchievement", "strongeraoe", function(player)
	player.components.allachivcoin:strongeraoecoin(player)
end)
AddModRPCHandler("DSTAchievement", "waxwellup", function(player)
	player.components.allachivcoin:waxwellupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "winnonaup", function(player)
	player.components.allachivcoin:winnonaupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "woodieup", function(player)
	player.components.allachivcoin:woodieupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "warlyup", function(player)
	player.components.allachivcoin:warlyupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "wormwoodup", function(player)
	player.components.allachivcoin:wormwoodupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "wickerbottomup", function(player)
	player.components.allachivcoin:wickerbottomupcoin(player)
end)
AddModRPCHandler("DSTAchievement", "callback", function(player)
	player.components.allachivcoin:callbackcoin(player)
end)
AddModRPCHandler("DSTAchievement", "lightpower", function(player)
	player.components.allachivcoin:lightpowercoin(player)
end)
AddModRPCHandler("DSTAchievement", "hitattack", function(player)
	player.components.allachivcoin:hitattackcoin(player)
end)
AddModRPCHandler("DSTAchievement", "throwrock", function(player)
	player.components.allachivcoin:throwrockcoin(player)
end)
AddModRPCHandler("DSTAchievement", "memorykill", function(player)
	player.components.allachivcoin:memorykillcoin(player)
end)
AddModRPCHandler("DSTAchievement", "quickshot", function(player)
	player.components.allachivcoin:quickshotcoin(player)
end)

