AddModRPCHandler("DSTExclusive", "potion", function(player)
	player.components.allachivcoin:potioncoin(player)
end)

--特殊
AddModRPCHandler("DSTAchievement", "level120", function(player)
	player.components.allachivcoin:level120coin(player)
end)
AddModRPCHandler("DSTExclusive", "abigaillevelup", function(player)
	player.components.allachivcoin:abigaillevelupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "abigailclone", function(player)
	player.components.allachivcoin:abigailclonecoin(player)
end)
AddModRPCHandler("DSTExclusive", "bloodangry", function(player)
	player.components.allachivcoin:bloodangrycoin(player)
end)
AddModRPCHandler("DSTExclusive", "balloonlevelup", function(player)
	player.components.allachivcoin:balloonlevelupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "ballooninspire", function(player)
	player.components.allachivcoin:ballooninspirecoin(player)
end)
AddModRPCHandler("DSTAchievement", "wescheat", function(player)
	player.components.allachivcoin:wescheatcoin(player)
end)
AddModRPCHandler("DSTExclusive", "callspider", function(player)
	player.components.allachivcoin:callspidercoin(player)
end)
AddModRPCHandler("DSTExclusive", "spiderstronger", function(player)
	player.components.allachivcoin:spiderstrongercoin(player)
end)
AddModRPCHandler("DSTExclusive", "bernielevelup", function(player)
	player.components.allachivcoin:bernielevelupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "linghtermore", function(player)
	player.components.allachivcoin:linghtermorecoin(player)
end)
AddModRPCHandler("DSTExclusive", "gearuse", function(player)
	player.components.allachivcoin:gearusecoin(player)
end)
AddModRPCHandler("DSTExclusive", "callmerm", function(player)
	player.components.allachivcoin:callmermcoin(player)
end)
AddModRPCHandler("DSTExclusive", "mermstronger", function(player)
	player.components.allachivcoin:mermstrongercoin(player)
end)
AddModRPCHandler("DSTExclusive", "soulmore", function(player)
	player.components.allachivcoin:soulmorecoin(player)
end)
AddModRPCHandler("DSTExclusive", "strongeraoe", function(player)
	player.components.allachivcoin:strongeraoecoin(player)
end)
AddModRPCHandler("DSTExclusive", "waxwellup", function(player)
	player.components.allachivcoin:waxwellupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "winnonaup", function(player)
	player.components.allachivcoin:winnonaupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "woodieup", function(player)
	player.components.allachivcoin:woodieupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "warlyup", function(player)
	player.components.allachivcoin:warlyupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "wormwoodup", function(player)
	player.components.allachivcoin:wormwoodupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "wickerbottomup", function(player)
	player.components.allachivcoin:wickerbottomupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "wandaup", function(player)
	player.components.allachivcoin:wandaupcoin(player)
end)
AddModRPCHandler("DSTExclusive", "callback", function(player)
	player.components.allachivcoin:callbackcoin(player)
end)
AddModRPCHandler("DSTExclusive", "lightpower", function(player)
	player.components.allachivcoin:lightpowercoin(player)
end)
AddModRPCHandler("DSTExclusive", "hitattack", function(player)
	player.components.allachivcoin:hitattackcoin(player)
end)
AddModRPCHandler("DSTExclusive", "throwrock", function(player)
	player.components.allachivcoin:throwrockcoin(player)
end)
AddModRPCHandler("DSTExclusive", "memorykill", function(player)
	player.components.allachivcoin:memorykillcoin(player)
end)
AddModRPCHandler("DSTExclusive", "quickshot", function(player)
	player.components.allachivcoin:quickshotcoin(player)
end)

