STRINGS.TITLE={
	{
		id="title1",
		name="初出江湖", 
		desc={"生存超过"..title_data["title1"]["age"].."天"},
		common={
			"关怀:生存艰难,基于世界天数/生存天数给予经验倍数关怀"
		},
		equip={
			"时运:每"..title_data["title1"]["days"].."天获得至少"..title_data["title1"]["luck"].."幸运值(基于世界天数)",
			"关照:忽略世界天数对于风滚草品质影响"
		},
		level=1,
	},
	{
		id="title2",
		name="初染血光", 
		desc={
			"完成成就【大杀四方】",
			"击杀任意四季领主一次"
		},
		common={
			"精通:经验获取提升"..(title_data["title2"]["exp"]*100).."%",
			"体术:每次升级恢复生命值"..(title_data["title2"]["health"]*100).."%",
			"精神:每次升级恢复理智"..(title_data["title2"]["sanity"]*100).."%",
		},
		equip={
			"杀意:对boss附加"..(title_data["title2"]["extra"]*100).."%额外伤害"
		},
		level=2,
	},
	{
		id="title3",
		name="美食专家", 
		desc={
			"完成所有烹饪成就",
			"完成隐藏成就【你是如何做到的】",
			"完成隐藏成就【我没蛋了】"
		},
		common={
			"厨技:吃肉食额外恢复"..(title_data["title3"]["hunger"]).."饥饿",
			"厨技:吃素食额外恢复"..(title_data["title3"]["sanity"]).."理智",
			"怜悯:【沃利】直接斩杀生命值小于"..(title_data["title3"]["lost_percent"]*100).."%的目标"
		},
		equip={
			"强健:饱食度大于"..(title_data["title3"]["hunger_percent"]*100).."%消耗1饥饿附加"..(title_data["title3"]["extra"]*100).."%额外伤害",
			--"盛宴:品尝美食时,降低敌方单位的攻击力"
		},
		level=4,
	},
	{
		id="title4",
		name="心灵手巧", 
		desc={
			"完成全部建造成就",
			"完成全部伤害要求成就",
			"完成全部交友成就"
		},
		common={
			"狩猎:击杀有"..(title_data["title4"]["drop"]*100).."%概率双倍掉落",
			"魔手:采集风滚草"..(title_data["title4"]["drop"]*100).."%概率多1份物品",
			"精工:【薇诺娜】提升投石机科技力量"
		},
		equip={
			"探云:攻击有"..(title_data["title4"]["steal"]*100).."%概率偷取物品",
			--"偷袭:背后攻击敌人时,必定暴击且【探云】成功概率翻倍"
		},
		level=3,
	},
	{
		id="title5",
		name="杀戮之心", 
		desc={
			"完成所有除大型BOSS外的击杀成就",
			"完成隐藏成就【超级暴击】",
			"击杀暴怒克劳斯",
			--"击杀冬天的熊獾",
		},
		common={
			"愤怒:暴击概率增加"..(title_data["title5"]["crit"]*100).."%",
			"嗜血:吸血效果增加"..(title_data["title5"]["stealhealth"]*100).."%",
			--"战技:【薇格弗德】受伤后提升闪避几率，最高"..(title_data["title5"]["miss"]*100).."%"
			"战技:【薇格弗德】完成击杀后【战斗技巧】直接满层"
		},
		equip={
			"疯狂:暴击的最大倍数+"..title_data["title5"]["hit"]
		},
		level=6,
	},
	{
		id="title6",
		name="死神附体", 
		desc={
			"完成成就【超鬼】",
			"前"..title_data["title6"]["cycle"].."天内死亡超过"..title_data["title6"]["death"].."次"
		},
		common={
			"怜悯:黄昏或夜晚复活后获得光源",
			"抗拒:死亡时对周围低级怪物强行催眠",
			"复仇:【温蒂】及阿比盖尔受伤后提升对该攻击者的伤害",
		},
		equip={
			"狂怒:死亡时对范围内进行爆炸",
		},
		level=2,
	},
	{
		id="title7",
		name="生生不息", 
		desc={
			"完成成就【救世主】",
			"完成成就【生生不息】",
			"前"..title_data["title7"]["cycle"].."天内死亡小于"..title_data["title7"]["death"].."次"
		},
		common={
			"恢复:击杀怪物恢复自身"..(title_data["title7"]["regen"]*100).."%敌人最大生命值",
			"神佑:受到伤害时,有"..(title_data["title7"]["direct"]*100).."%概率转移此次伤害到附近单位上",
		},
		equip={
			"谨慎:生命值小于"..(title_data["title7"]["health"]*100).."%时受到伤害会转移给随从",
		},
		level=3,
	},
	{
		id="title8",
		name="不离不弃", 
		desc={
			"完成隐藏成就【忠实的草迷】",
			"生存超过"..title_data["title8"]["age"].."天",
		},
		common={
			"兴奋:采集风滚草时恢复"..title_data["title8"]["sanity"].."点理智",
			"熟练:采集风滚草时同时采集范围内多个",
		},
		equip={
			"炼化:采集风滚草有"..(title_data["title8"]["up"]*100).."%概率提升周围风滚草的品质"
		},
		level=5,
	},
	{
		id="title9",
		name="悠然自得", 
		desc={
			"完成成就【生生不息】",
			"完成成就【收割机】",
			"完成成就【矿老板】",
			"完成成就【小当家】",
		},
		common={
			"强身:永久提升生命值"..title_data["title9"]["health"].."点",
			"健魄:永久提升理智"..title_data["title9"]["sanity"].."点",
			"生长:【沃姆伍德】种植作物获得额外经验，随生存天数获得额外成长",
		},
		equip={
			"悠然:种植，收割，挖矿，烹饪获得一定经验值",
			"蓄力:非战斗状态下提升下次额外攻击力，悠然提升更多效果",
		},
		level=4,
	},
	{
		id="title10",
		name="天选之子", 
		desc={
			"完成隐藏成就【超级幸运儿】",
			"完成隐藏成就【真正的宝贝】",
			"生存天数大于"..title_data["title10"]["age"],
		},
		common={
			"天选:幸运值低于"..title_data["title10"]["luck"].."时，任何事件有"..(title_data["title10"]["luckup"]*100).."%几率增加幸运值",
			"绝境:受到致命伤害时,有"..(title_data["title10"]["live"]*100).."%概率消耗幸运值抵挡该次伤害",
		},
		equip={
			"注灵:制作武器时，高幸运值有概率制作出极品武器",
			"鸿运:幸运值高于"..title_data["title10"]["luck"].."时,每次攻击必定3倍及以上暴击并消耗幸运",
		},
		level=5,
	},
	{
		id="title11",
		name="诅咒之躯", 
		desc={
			"完成成就【你对力量一无所知】",
			"一天之内遭遇"..title_data["title11"]["trap"].."次风滚草陷阱",
			"生存天数大于"..title_data["title11"]["age"],
			"未获得【天选之子】称号",
		},
		common={
			"灾厄:幸运值低于"..title_data["title11"]["luck"].."时，附加"..(title_data["title11"]["extra"]*100).."%额外伤害",
			
		},
		equip={
			"命运:攻击有"..(title_data["title11"]["per"]*100).."%概率消耗武器所有耐久一次性造成"..(title_data["title11"]["damage"]*100).."%伤害",
		},
		level=5,
	},
	{
		id="title12",
		name="王者之巅", 
		desc={
			"完成所有成就，重复成就和隐藏成就除外",
			"生存天数大于"..title_data["title12"]["age"],
			"等级大于"..title_data["title12"]["level"],
		},
		common={
			"洒脱:提升"..(title_data["title12"]["speed"]*100).."%移动速度",
			"瞬身:提升"..(title_data["title12"]["miss"]*100).."%闪避",
			"蔑视:对小怪伤害提升"..(title_data["title12"]["damageup"]*100).."%",
		},
		equip={
			"便捷:可以使用部分便捷指令",
			"威望:提升萤火微光范围,每天可以领取一次物资",
		},
		level=7,
	},
	{
		id="title13",
		name="次元之客", 
		desc={
			"*尊贵的客人凭证*",
		},
		common={
			"精通:经验获取提升"..(title_data["title13"]["exp"]*100).."%",
			"魔手:采集风滚草多获得一份物品",
			"优惠:复活CD减少"..(title_data["title13"]["resurrect"]*100).."%,*空间权杖升级,其他隐藏福利*",
		},
		equip={
			"好运:采集风滚草有"..(title_data["title13"]["luck"]*100).."%概率增加幸运",
			"特权:*可以使用便捷指令",
		},
		level=9,
	},
	{
		id="title14",
		name="天外飞仙", 
		desc={
			"*朋友，我这里有一本飞仙秘籍*",
		},
		common={
			"一阶:#RGB",
			"二阶:*"
		},
		equip={
			"飞仙:*",
		},
		level=8,
	}
}
STRINGS.CMDS={
	["call"] = "需要我的帮助:发送指令#go立即援助",
	["called"] = "成功发送援助信息",
	["notarget"] = "暂时没有需要帮助的伙伴",
}